### ISSUE TITLE
IE,Firefox : Scroll Horizontal Problem

### ISSUE THREAD

**Issue by giangvt** [davetayls/jquery.kinetic#95]
When I use this library for datatable in IE, Firefox (work fine only on Chrome), I found problem about Scroll Horizontal.
When I drag scroll horizontal and release mouse, position of scroll horizontal is not correct. You can see in my demo image ( .gif animation).

Please help me to resolve this problem.
![scrollhorizontal ie](https://cloud.githubusercontent.com/assets/10720046/14164960/705033d6-f72e-11e5-851f-1e9eee513663.gif)

![scrollhorizontal firefox](https://cloud.githubusercontent.com/assets/10720046/14165068/486887fa-f72f-11e5-9538-cf701ab6ad85.gif)

**Comment by davetayls** [comment]
It's been a long time since I worked with this plugin but i don't think it expects scrollbars to be visible and your gifs suggest that it's picking up mouse movement from clicking on the bars when it shouldn't. You might be able to fix this within a filterTarget check based on how close the mouse is to the bottom of the kinetic div.

I'm going to close this as it's very old though.
